config/routes.rb
Rails.application.routes.draw do
  # get 'fileuploads/index'
  #
  # get 'fileuploads/create'
  #
  # get 'fileuploads/new'

  resources :fileuploads, only: [:index, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fileuploads_controller.rb
class FileuploadsController < ApplicationController
  def index
	  @img_paths = []
	  jpgs = Dir.glob(Rails.root.join('public', '*.jpg'))
	  jpgs.each do |png|
		  @img_paths.push('/'+File.basename(png))
	  end
  end

  def create
	  uploaded_file = fileupload_param[:file]
	  output_path = Rails.root.join('public', uploaded_file.original_filename)

	  File.open(output_path, 'w+b') do |fp|
		  fp.write uploaded_file.read
	  end

	  redirect_to action: 'index'
  end

  def new
  end

  private
  def fileupload_param
	  params.require(:fileupload).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fileuploads_helper.rb
module FileuploadsHelper
end

app/views/fileuploads/create.html.erb
<h1>Fileuploads#create</h1>
<p>Find me in app/views/fileuploads/create.html.erb</p>

app/views/fileuploads/index.html.erb
<h1><%= link_to 'Append jpg', new_fileupload_url %></h1>
<% @img_paths.each do |img_path| %>
	<img src="http://localhost:3000/<%= img_path %>">
<% end %>

app/views/fileuploads/new.html.erb
<%= form_tag '/fileuploads', methods: 'post', multipart: true do %>
	<label>ファイル</label>
	<%= file_field :fileupload, :file %>

	<%= submit_tag 'Send file' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>